---
- name: install virtualbox dependencies
  ansible.builtin.package:
    name: "{{ packages }}"
  vars:
    packages:
      - binutils
      - gcc
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - dkms
      - wget

- name: add virtualbox repository
  ansible.builtin.copy:
    src: files/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo
    owner: root
    group: root
    mode: "0644"
  register: virtualbox_repository

- name: add virtualbox repository gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://www.virtualbox.org/download/oracle_vbox.asc

- name: get kernel version
  ansible.builtin.shell: |
    set -o pipefail
    uname -r | egrep -o '^[0-9]*\.[0-9]*\.[0-9]*'
  args:
    executable: /bin/bash
  register: virtualbox_kernel_version
  changed_when: false

- name: install kernel-devel and kernel-headers
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kernel-devel-{{ virtualbox_kernel_version.stdout }}
      - kernel-headers-{{ virtualbox_kernel_version.stdout }}

- name: install VirtualBox
  ansible.builtin.package:
    name: VirtualBox-{{ virtualbox_version }}
    state: present
  register: virtualbox_installed

- name: run vboxdrv setup
  ansible.builtin.shell: /usr/lib/virtualbox/vboxdrv.sh setup
  when: virtualbox_installed.changed
  register: virtualbox_vboxdrv
  ignore_errors: true

- name: Check if extension pack is already installed
  ansible.builtin.shell: VBoxManage list extpacks
  register: virtualbox_extpack_list

- name: Download VirtualBox extension pack
  ansible.builtin.get_url:
    validate_certs: true
    url: "{{ virtualbox_extension_pack_url }}"
    dest: /tmp
    mode: "0700"
  when: 'virtualbox_extpack_list.stdout == "Extension Packs: 0"'
  register: virtualbox_extension_pack

- name: Install VirtualBox extension pack
  ansible.builtin.shell: |
    set -o pipefail
    echo y | VBoxManage extpack install --replace {{ virtualbox_extension_pack.dest }}
    rm -f "{{ virtualbox_extension_pack.dest }}"
  args:
    executable: /bin/bash
  when: 'virtualbox_extpack_list.stdout == "Extension Packs: 0"'

- name: hashicorp repo
  ansible.builtin.get_url:
    validate_certs: true
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    owner: root
    group: root
    mode: "0644"

- name: install vagrant
  ansible.builtin.dnf:
    name: vagrant
    state: present

- name: failed to install VritualBox
  ansible.builtin.fail:
    msg: '"failed to install VritualBox"'
  when: ((virtualbox_vboxdrv is failed) and (not virtualbox_role_debug|bool))
